"""Pluggable blob storage.

Two implementations sit behind one Protocol:

  LocalDiskStorage   -- default; used by the whole test suite so tests run offline.
  GoogleDriveStorage -- private Drive folder via a service account.

The Drive files are deliberately NEVER link-shared. The service reads them with its
own credentials and streams the bytes to the visitor. A public Drive link would be
reachable independently of this service, which would make expiry and revocation
decorative rather than real (spec decision D2/D3).
"""

from __future__ import annotations

import io
import uuid
from pathlib import Path
from typing import Iterator, Protocol

CHUNK_SIZE = 64 * 1024


class StorageError(RuntimeError):
    pass


class Storage(Protocol):
    def save(self, data: bytes, *, filename: str, content_type: str) -> str:
        """Persist bytes and return an opaque reference for later retrieval."""

    def open_stream(self, ref: str) -> Iterator[bytes]:
        """Yield the stored bytes in chunks. Raises StorageError if ref is unknown."""

    def delete(self, ref: str) -> None: ...


class LocalDiskStorage:
    def __init__(self, root: Path) -> None:
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, ref: str) -> Path:
        # ref is generated by us (a uuid4 hex); reject anything that could escape root.
        if "/" in ref or "\\" in ref or ".." in ref:
            raise StorageError(f"invalid storage ref: {ref!r}")
        return self.root / ref

    def save(self, data: bytes, *, filename: str, content_type: str) -> str:
        ref = f"{uuid.uuid4().hex}.bin"
        tmp = self._path(ref + ".tmp")
        tmp.write_bytes(data)
        # Atomic publish: a reader can never observe a half-written blob.
        tmp.replace(self._path(ref))
        return ref

    def open_stream(self, ref: str) -> Iterator[bytes]:
        path = self._path(ref)
        if not path.exists():
            raise StorageError(f"missing blob: {ref}")

        def _gen() -> Iterator[bytes]:
            with path.open("rb") as fh:
                while chunk := fh.read(CHUNK_SIZE):
                    yield chunk

        return _gen()

    def delete(self, ref: str) -> None:
        self._path(ref).unlink(missing_ok=True)


class GoogleDriveStorage:
    """Service-account backed Drive storage.

    Requires `google-api-python-client` and `google-auth`, a service-account JSON key,
    and a folder the service account can write to. On a personal Gmail account the
    service account must OWN the folder; on Workspace a shared drive is cleaner.
    """

    DEFAULT_SCOPE = "https://www.googleapis.com/auth/drive.file"

    def __init__(
        self,
        service_account_file: Path,
        folder_id: str,
        scope: str | None = None,
    ) -> None:
        if not folder_id:
            raise StorageError("drive_folder_id is not configured")
        if not Path(service_account_file).exists():
            raise StorageError(
                f"service account key not found at {service_account_file}"
            )
        # Imported lazily so the local backend has no Google dependency at runtime.
        from google.oauth2 import service_account  # noqa: PLC0415
        from googleapiclient.discovery import build  # noqa: PLC0415

        creds = service_account.Credentials.from_service_account_file(
            str(service_account_file), scopes=[scope or self.DEFAULT_SCOPE]
        )
        self._service = build("drive", "v3", credentials=creds, cache_discovery=False)
        self.folder_id = folder_id

    def save(self, data: bytes, *, filename: str, content_type: str) -> str:
        from googleapiclient.http import MediaIoBaseUpload  # noqa: PLC0415

        media = MediaIoBaseUpload(
            io.BytesIO(data), mimetype=content_type, resumable=False
        )
        created = (
            self._service.files()
            .create(
                body={"name": filename, "parents": [self.folder_id]},
                media_body=media,
                fields="id",
                supportsAllDrives=True,
            )
            .execute()
        )
        return created["id"]

    def open_stream(self, ref: str) -> Iterator[bytes]:
        from googleapiclient.errors import HttpError  # noqa: PLC0415
        from googleapiclient.http import MediaIoBaseDownload  # noqa: PLC0415

        buf = io.BytesIO()
        try:
            request = self._service.files().get_media(
                fileId=ref, supportsAllDrives=True
            )
            downloader = MediaIoBaseDownload(buf, request, chunksize=CHUNK_SIZE)
            done = False
            while not done:
                _, done = downloader.next_chunk()
        except HttpError as exc:  # pragma: no cover - needs live Drive
            raise StorageError(f"drive fetch failed for {ref}: {exc}") from exc
        buf.seek(0)

        def _gen() -> Iterator[bytes]:
            while chunk := buf.read(CHUNK_SIZE):
                yield chunk

        return _gen()

    def delete(self, ref: str) -> None:  # pragma: no cover - needs live Drive
        from googleapiclient.errors import HttpError  # noqa: PLC0415

        try:
            self._service.files().delete(fileId=ref, supportsAllDrives=True).execute()
        except HttpError as exc:
            raise StorageError(f"drive delete failed for {ref}: {exc}") from exc


def build_storage(settings) -> Storage:
    if settings.storage_backend == "drive":
        return GoogleDriveStorage(
            settings.google_service_account_file,
            settings.drive_folder_id,
            settings.drive_scope,
        )
    return LocalDiskStorage(settings.storage_dir)
